/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComponentesTela.java
 *
 * Created on Mar 16, 2009, 1:13:05 PM
 */

package com.jdf.swing.helper;

import com.jdf.database.bean.Aluno;
import com.jdf.swing.iface.IconPackBase64;
import com.jdf.util.Propriedades;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPopupMenu;

/**
 *
 * @author rafael-lossurdo
 */
public class ComponentesTela extends javax.swing.JFrame {

    /** Creates new form ComponentesTela */
    public ComponentesTela() {
        initComponents();
        
        // formata frame principal        
        JFrameHelper jfh = new JFrameHelper(this);
        jfh.setBigSize();
        jfh.setIcon(IconPackBase64.BOMB);
        jfh.setTitle(Propriedades.getInstance().get("sistema.titulo"));
        jfh.centerFrame();
        
        // formata botões
        JButtonHelper jbh1 = new JButtonHelper(btnVisualizaCombo);
        jbh1.setIcon(IconPackBase64.BUG);
        JButtonHelper jbh2 = new JButtonHelper(btnVisualizaListSimples);
        jbh2.setIcon(IconPackBase64.CART);
        
        // lista usada para listagens
        List<Aluno> alunos = new ArrayList<Aluno>();
        alunos.add(new Aluno(1,"Rafael Lossurdo"));
        alunos.add(new Aluno(2,"Queisi Oliveira"));
        alunos.add(new Aluno(3,"João da Silva"));
        List<Aluno> alunos2 = new ArrayList<Aluno>();
        alunos2.add(new Aluno(4,"Ana Maria"));
        alunos2.add(new Aluno(2,"Carlos Eduardo"));
        alunos2.add(new Aluno(5,"Giovanna da Silva"));
        
        // seta combo box
        jc = new JComboBoxHelper(comboBox);
        jc.setModel(alunos);
        
        // seta listbox simples 
        jlh = new JListHelper(listUnico);
        jlh.setModel(alunos);  
        
        // seta listbox complexo n:n
        JListHelper jlhComplexo = new JListHelper(listEsq, listDir, btnTodosDir, btnTodosEsq, btnDir, btnEsq);
        jlhComplexo.setModelLeft(alunos);
        jlhComplexo.setModelRight(alunos2);
        jlhComplexo.applyListeners();
        
        // modifica ícone dos botões n:n
        new JButtonHelper(btnTodosDir).setIcon(IconPackBase64.ARROW_TURN_RIGHT);
        new JButtonHelper(btnTodosEsq).setIcon(IconPackBase64.ARROW_TURN_LEFT);
        new JButtonHelper(btnDir).setIcon(IconPackBase64.ARROW_RIGHT);
        new JButtonHelper(btnEsq).setIcon(IconPackBase64.ARROW_LEFT);
        
        // link para browser
        JLabelHelper lh = new JLabelHelper(jLabel1);
        try {
			lh.transformToURLLink(new URI("http://www.terra.com.br"), JLabelHelper.DEFAULT_TOOLTIP);
		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
		
		// popup menu
		JPopupMenuHelper pp = new JPopupMenuHelper(new JPopupMenu("Meu Menu"), this);
		pp.addMenu("Teste A", 'A').
			addItem(null, null, "AAA", IconPackBase64.BASKET).
			addItem(null, null, "BBB");
		pp.addSeparator();
		pp.addMenu("Teste B", 'B').
			addItem(null, null, "CCC").
			addItem(null, null, "CCC").
			addItem(null, null, "CCC").
			addSeparator().
			addItem(null, null, "DDD");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox();
        btnVisualizaCombo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUnico = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEsq = new javax.swing.JList();
        btnTodosDir = new javax.swing.JButton();
        btnDir = new javax.swing.JButton();
        btnEsq = new javax.swing.JButton();
        btnTodosEsq = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDir = new javax.swing.JList();
        btnVisualizaListSimples = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Combo box");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVisualizaCombo.setText("Visualizar Objeto Selecionado");
        btnVisualizaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizaComboActionPerformed(evt);
            }
        });

        jLabel2.setText("List box");

        listUnico.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listUnico);

        jLabel3.setText("List box N:N");

        listEsq.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEsq);

        btnTodosDir.setText("Todos");

        btnDir.setText("Mover");

        btnEsq.setText("Mover");

        btnTodosEsq.setText("Todos");

        listDir.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listDir);

        btnVisualizaListSimples.setText("Visualizar Objeto Selecionado");
        btnVisualizaListSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizaListSimplesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizaListSimples))
                    .addComponent(jLabel1)
                    .addComponent(btnVisualizaCombo)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTodosDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEsq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTodosEsq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisualizaCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVisualizaListSimples))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnTodosDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEsq)
                                .addGap(18, 18, 18)
                                .addComponent(btnTodosEsq))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizaComboActionPerformed
        JOptionPaneHelper.warning(jc.getSelectedObject().toString());
    }//GEN-LAST:event_btnVisualizaComboActionPerformed

    private void btnVisualizaListSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizaListSimplesActionPerformed
        JOptionPaneHelper.warning(jlh.getSelectedObject().toString());
    }//GEN-LAST:event_btnVisualizaListSimplesActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComponentesTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDir;
    private javax.swing.JButton btnEsq;
    private javax.swing.JButton btnTodosDir;
    private javax.swing.JButton btnTodosEsq;
    private javax.swing.JButton btnVisualizaCombo;
    private javax.swing.JButton btnVisualizaListSimples;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listDir;
    private javax.swing.JList listEsq;
    private javax.swing.JList listUnico;
    // End of variables declaration//GEN-END:variables
	private JComboBoxHelper jc;
	private JListHelper jlh;

}
